spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/credit
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
loan:
  minimalIncome: 40000
  maxCreditRateFromIncome: 0.5
  minCarPriceForLoan: 1000000
  maxCreditRateFromCarPrice: 0.3
external:
  api:
    incomes: "https://66055cd12ca9478ea1801f2e.mockapi.io/api/users/income"
